### ISSUE TITLE
Second !!

### ISSUE THREAD

**Issue by ChristianBdv** [stegers/insta-timestamp#1]
Hello Stegers
I used your script during a challenge in which I participated on the account of https://manuelbot59.github.io/ManuelBot59.html
We had to indicate the exact date and time of a publication, but your script did not indicate the seconds...
I added these instructions after the minute function:
, second: 'numeric'
This clarification completes the information in the json tag present in the Instagram code.
If you could include it please
Long life to your deposit!!

**Comment by ManuelBot59** [comment]
Cool!

**Comment by stegers** [comment]
It's now included. Thanks for the suggestion.
